# Dockerfile.prod

# Stage 1: Build React app
FROM node:24 AS builder

WORKDIR /app
COPY package.json ./
RUN npm install
COPY . .
RUN npm run build

# Stage 2: No need to copy anything to the final image, just to extract build
