# Use Node.js base image
FROM node:24

# Upgrade npm to the latest version
RUN npm install -g npm@11.4.1

# Set working directory inside container
WORKDIR /app

# Copy only package.json and package-lock.json to install deps
COPY package*.json ./

# Install dependencies (including react-scripts)
RUN npm install

# Copy rest of the app
COPY . .

# Expose the React dev server port
EXPOSE 3000

# Start the React app
CMD ["npm", "run","dev"]
